name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test_git_version_action:
    runs-on: ubuntu-latest
    name: 'Test GHA'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Get version'
        uses: ./
